version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    hostname: db-postgresql
    env_file:
      - ./env.properties
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    expose:
      - "${POSTGRESDB_DOCKER_PORT}"
    ports:
      - "${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}"
    networks:
      - app-network

  app:
    image: my-task-board-api:v1
    container_name: my-task-board
    restart: on-failure
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: ${POSTGRESDB_DOCKER_URL}
      SPRING.DATASOURCE.USERNAME: ${POSTGRESDB_USER}
      SPRING.DATASOURCE.PASSWORD: ${POSTGRESDB_PASSWORD}
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    command: mvn spring-boot:run
    networks:
      - app-network

networks:
  app-network:
    driver: bridge