server:
  port: 8080
cors:
  originPatterns: http://localhost:4200,http://localhost:3000,http://localhost:8080
  allowed-origins: http://localhost:4200,http://localhost:3000,http://localhost:8080
  allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
  max-age: 3600
  allowed-headers: "Requestor-Type"
  exposed-headers: "X-Get-Header"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRESDB_LOCAL_URL}
    username: ${POSTGRESDB_USER}
    password: ${POSTGRESDB_PASSWORD}
    hikari:
      auto-commit: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  jackson:
    time-zone: America/Sao_Paulo
springdoc:
  pathsToMatch:
    - /api/v1/**/
  swagger-ui:
    use-root-path: true