server:
  port: 8080
cors:
  originPatterns: http://localhost:4200,http://localhost:3000,http://localhost:8080
  allowed-origins: http://localhost:4200,http://localhost:3000,http://localhost:8080
  allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
  max-age: 3600
  allowed-headers: "Requestor-Type"
  exposed-headers: "X-Get-Header"
spring:
  config:
    import: env.properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my-task-board?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ${POSTGRESDB_USER}
    password: ${POSTGRESDB_ROOT_PASSWORD}
    hikari:
      auto-commit: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: db/migration
  jackson:
    time-zone: America/Sao_Paulo
springdoc:
  pathsToMatch:
    - /api/v1/**/
  swagger-ui:
    use-root-path: true